name: sqljocky5
version: 2.2.0
description: MySQL driver for Dart
documentation:
homepage: https://github.com/dart-db/sqljocky5

authors:
- James Ots <code@jamesots.com>
- Ravi Teja Gudapati <tejainece@gmail.com>

environment:
  sdk: '>=2.0.0-dev.68.0 <3.0.0'

dependencies:
  collection: ^1.1.3
  crypto: ^2.0.6
  logging: ^0.11.3
  pool: ^1.3.6
  typed_buffer: ^2.1.1

dev_dependencies:
  test: ^1.3.0
