name: sqljocky5
version: 2.2.1
description: MySQL driver for Dart
documentation:
homepage: https://github.com/dart-db/sqljocky5

authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- James Ots <code@jamesots.com>

environment:
  sdk: '>=2.0.0-dev.68.0 <3.0.0'

dependencies:
  collection: ^1.1.3
  crypto: ^2.0.6
  synchronized: ^1.5.1
  typed_buffer: ^2.1.1

dev_dependencies:
  test: ^1.3.0
